### ISSUE TITLE
How is the similarity between descriptors calculated?

### ISSUE THREAD

**Issue by SlamCabbage** [LiHeUA/M2DP#2]
Excuse me, how is the similarity between descriptors calculated?

**Comment by LiHeUA** [comment]
Hi there,
Just the L2 distance between two vectors.



----
Li He
Research Associate Professor, Department of Electrical and Electronic Engineering, Southern University of Science and Technology, China

发件人: Adam ***@***.***>
发送时间: 2022年11月10日 17:43
收件人: ***@***.***>
抄送: ***@***.***>
主题: [LiHeUA/M2DP] How is the similarity between descriptors calculated? (Issue #2)


Excuse me, how is the similarity between descriptors calculated?

―

**Comment by SlamCabbage** [comment]
thanks a lot for your answer.
